// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlzcukkqfjdaclrfcuml.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsemN1a2txZmpkYWNscmZjdW1sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjkwMTAwOTYsImV4cCI6MjA4NDU4NjA5Nn0.RRn9pxWOvc0pEIhfG3OrWvRk3zTHVUv_hlEQTqgM3Gs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});